### ISSUE TITLE
Is OpenAPI 2 also supported?

### ISSUE THREAD

**Issue by mastoj** [criteo/openapi-comparator#20]
We have a mix of v3 and v2 versions, are the tool capable of comparing both versions?

**Comment by ouvreboite** [comment]
Hello :)
Internally, the comparator use [microsoft/OpenAPI.NET](https://github.com/microsoft/OpenAPI.NET) to deserialize the OAS. So it should be able to read an OASv2, but it will be converted to v3 internally.

This means:
- There may be some stuff lost in translation during the v2 -> v3 conversion
- Even if you compare v2 specifications, the differences will be expressed in the v3 syntax.
