### ISSUE TITLE
Support for YAML

### ISSUE THREAD

**Issue by davidkeaveny** [criteo/openapi-comparator#28]
Would it be possible to add support for YAML? YAML is a common format for OpenAPI specifications, and mostly similar to JSON.

**Comment by bubianchi-criteo** [comment]
Yes, we agree that YAML should be supported. All the more reason, it is natively supported by Microsoft OpenApi...
At first analysis, it would require a significant internal redesign of the comparator.
So there is no quick win solution for now, but we keep this valid request in our todo list.
