### ISSUE TITLE
Erroneous 1015 detected in case where parameter name appears twice

### ISSUE THREAD

**Issue by hexthedev** [criteo/openapi-comparator#49]
Hello. Your tool is a life saver. 

Been using it for a few months, and we came across an edge case that seems to be a bug. 

We added an `access_token` parameter as either a header or a query parameter. The below image is a diff. There arn't actually any changes between the left and right side.
<img width="812" alt="image" src="https://github.com/user-attachments/assets/532b4922-616c-42fd-8592-e2d88d633381">

Now all comparisons between versions fail because they detect 1015 - How parameter passed has changed:

I have a hunch that it's because the comparison between sets of parameters does not check if the same method exists before checking if some other method exists:

I.E. I think the comparator currently does this:
* if parameter is query does new parameter contain header with same name. If so 1015 error

It should
* if parameter is query does new parameter contain query. If so, continue
* else if parameter is query does new parameter contain header with same name. If so 1015 error

**Comment by ouvreboite** [comment]
Should be fixed by https://github.com/criteo/openapi-comparator/pull/50
